version: '3'
services:
  suricata:
    image: jasonish/suricata:6.0.4
    command: -i ${INTERFACE?missing interface}
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    volumes:
      - ./suricata/config:/etc/suricata
      - ${NSM_LOG_DIR?missing nsm directoy}/suricata:/var/log/suricata:z
    network_mode: "host"
  zeek:
    build:
      context: ./zeek
    command: -i ${INTERFACE?missing interface}
    cap_add:
      - NET_ADMIN
    volumes:
      - ${NSM_LOG_DIR}/zeek:/var/log/zeek:z
    network_mode: "host"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    volumes:
     #- ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
     - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
#      ELASTIC_PASSWORD: changeme
      discovery.type: single-node
    networks:
     - elk
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.16.3
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./filebeat/modules.d/:/usr/share/filebeat/modules.d:ro
#      - :/usr/share/filebeat/logs
      -  ${NSM_LOG_DIR}/:/var/log/nsm/:z
    networks:
      - elk
    depends_on:
      - kibana
      - elasticsearch
    links:
       - elasticsearch
       - kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.3
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
#      ELASTICSEARCH_USERNAME: elastic
#      ELASTICSEARCH_PASSWORD: changeme
    ports:
      - 5601:5601
    networks:
      - elk
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

networks:  
  elk:
    driver: bridge

volumes:
  elasticsearch:
